'use strict';

const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('jot', {
  bootstrap: () => ipcRenderer.invoke('app:bootstrap'),
  recordShortcut: enabled => ipcRenderer.invoke('shortcut:record', enabled),
  listMeetings: query => ipcRenderer.invoke('meeting:list', query),
  getMeeting: id => ipcRenderer.invoke('meeting:get', id),
  createMeeting: options => ipcRenderer.invoke('meeting:create', options),
  startMeeting: options => ipcRenderer.invoke('meeting:start', options),
  pauseMeeting: () => ipcRenderer.invoke('meeting:pause'),
  resumeMeeting: () => ipcRenderer.invoke('meeting:resume'),
  stopMeeting: () => ipcRenderer.invoke('meeting:stop'),
  updateMeeting: (id, patch) => ipcRenderer.invoke('meeting:update', id, patch),
  deleteMeeting: id => ipcRenderer.invoke('meeting:delete', id),
  retryMeeting: id => ipcRenderer.invoke('meeting:retry', id),
  exportMeeting: (id, format) => ipcRenderer.invoke('meeting:export', id, format),
  openMeetingAudio: (id, source) => ipcRenderer.invoke('meeting:open-audio', id, source),
  meetingAudio: (id, source) => ipcRenderer.invoke('meeting:audio', id, source),
  calendarStatus: () => ipcRenderer.invoke('calendar:status'),
  calendarConfigure: config => ipcRenderer.invoke('calendar:configure', config),
  calendarConnect: () => ipcRenderer.invoke('calendar:connect'),
  calendarDisconnect: () => ipcRenderer.invoke('calendar:disconnect'),
  calendarRefresh: () => ipcRenderer.invoke('calendar:refresh'),
  mcpStatus: () => ipcRenderer.invoke('mcp:status'),
  mcpConfig: client => ipcRenderer.invoke('mcp:config', client),
  mcpTest: () => ipcRenderer.invoke('mcp:test'),
  updateMcp: patch => ipcRenderer.invoke('mcp:update', patch),
  listConnectors: () => ipcRenderer.invoke('connectors:list'),
  connectorList: () => ipcRenderer.invoke('connectors:list'),
  connectorSave: config => ipcRenderer.invoke('connectors:save', config),
  connectorRemove: id => ipcRenderer.invoke('connectors:remove', id),
  connectorInspect: id => ipcRenderer.invoke('connectors:inspect', id),
  saveConnector: config => ipcRenderer.invoke('connectors:save', config),
  removeConnector: id => ipcRenderer.invoke('connectors:remove', id),
  inspectConnector: id => ipcRenderer.invoke('connectors:inspect', id),
  callConnectorTool: value => ipcRenderer.invoke('connectors:call', value),
  transformText: value => ipcRenderer.invoke('text:transform', value),
  onMeetingsChanged: callback => ipcRenderer.on('meetings:changed', () => callback()),
  onMeetingState: callback => ipcRenderer.on('meeting:state', (_event, value) => callback(value)),
  onMeetingLevels: callback => ipcRenderer.on('meeting:levels', (_event, value) => callback(value)),
  onMeetingProgress: callback => ipcRenderer.on('meeting:progress', (_event, value) => callback(value)),
  onCalendarState: callback => ipcRenderer.on('calendar:state', (_event, value) => callback(value)),
  onSettingsChanged: callback => ipcRenderer.on('settings:changed', (_event, value) => callback(value)),
  onServicesReady: callback => ipcRenderer.on('services:ready', () => callback()),
  updateSettings: (patch) => ipcRenderer.invoke('settings:update', patch),
  saveApiKey: (key) => ipcRenderer.invoke('api-key:save', key),
  clearApiKey: () => ipcRenderer.invoke('api-key:clear'),
  listHistory: (query) => ipcRenderer.invoke('history:list', query),
  deleteHistory: (id) => ipcRenderer.invoke('history:delete', id),
  retryHistory: (id) => ipcRenderer.invoke('history:retry', id),
  copyHistory: (text) => ipcRenderer.invoke('history:copy', text),
  openAudio: (id) => ipcRenderer.invoke('history:open-audio', id),
  exportHistory: (id) => ipcRenderer.invoke('history:export', id),
  startDictation: () => ipcRenderer.invoke('dictation:start'),
  stopDictation: () => ipcRenderer.invoke('dictation:stop'),
  cancelDictation: () => ipcRenderer.invoke('dictation:cancel'),
  pasteLast: () => ipcRenderer.invoke('dictation:paste-last'),
  audioChunk: (data, sampleRate) => ipcRenderer.send('audio:chunk', { data, sampleRate }),
  audioLevel: (level) => ipcRenderer.send('audio:level', level),
  audioDevices: () => ipcRenderer.invoke('audio:devices'),
  openExternal: (url) => ipcRenderer.invoke('external:open', url),
  hideWindow: () => ipcRenderer.send('window:hide'),
  showWindow: () => ipcRenderer.send('window:show'),
  hudInteractive: value => ipcRenderer.send('hud:interactive', Boolean(value)),
  hudDrag: phase => ipcRenderer.send('hud:drag', phase),
  showHud: () => ipcRenderer.send('hud:show'),
  hideHud: () => ipcRenderer.send('hud:hide'),
  hudStart: () => ipcRenderer.send('hud:start'),
  hudStop: () => ipcRenderer.send('hud:stop'),
  onNavigate: (callback) => ipcRenderer.on('navigate', (_event, value) => callback(value)),
  onState: (callback) => ipcRenderer.on('dictation:state', (_event, value) => callback(value)),
  onAudioCommand: (callback) => ipcRenderer.on('audio:command', (_event, value) => callback(value)),
  onHistoryChanged: (callback) => ipcRenderer.on('history:changed', callback),
  onDiagnostic: (callback) => ipcRenderer.on('diagnostic', (_event, value) => callback(value)),
  onHudState: (callback) => ipcRenderer.on('hud:state', (_event, value) => callback(value)),
  onHudLevel: (callback) => ipcRenderer.on('hud:level', (_event, value) => callback(value))
});
